# inspect the methods loaded in this module and their usage
# in the rails console by just typing:
# >> puts Search.flex.doc
# you can eventually restrict the doc to a single method by pasing its name:
# >> puts Search.flex.doc :search
# see the detailed doc for this feature at http://ddnexus.github.io/flex/doc/2-flex/4-Self-Documentation.html

module Search

  extend self

  # if you don't use flex scopes and you stick with flex templates, you can comment the next line
  include Flex::Scopes

  # enables the templating
  include Flex::Templates
  # loads the search.yml file
  flex.load_search_source

  # you may need to add more method here, usually custom scopes
  # or wrapper methods that use one of the autogenerated methods from the loaded templates

end
